name: __av__nnenum

channels:
  - conda-forge
  - nodefaults  # Explicitly block Anaconda repos

dependencies:
  # Critical pinned packages
  - python=3.9
  - numpy=1.23.2
  - scipy=1.9.0
  
  # Core dependencies
  - pip
  - scikit-learn
  - sympy
  - pip:
      - absl-py==1.4.0
      - charset-normalizer==3.1.0
      - coloredlogs==15.0.1
      - flatbuffers==23.3.3
      - humanfriendly==10.0
      - idna==3.4
      - joblib==1.2.0
      - mpmath==1.3.0
      - numpy==1.23.2
      - onnx==1.12.0
      - onnxconverter-common==1.13.0
      - onnxruntime==1.12.1
      - requests==2.28.2
      - scikit-learn==1.2.2
      - scipy==1.9.0
      - skl2onnx==1.12
      - swiglpk==5.0.8
      - sympy==1.11.1
      - threadpoolctl==3.1.0
      - termcolor==2.2.0
      - urllib3==1.26.15
